<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
name="ConsultaProveedores" 
targetNamespace="http://www.caracoltv.com.co/TI/xcalibur/consultaproveedores/" 
xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
xmlns:mex="http://www.cysce.com/csif-msg/ca/fault/v1.0/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:srv="http://www.caracoltv.com.co/TI/xcalibur/consultaproveedores/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="bdxcaliburconsultaProveedoresSOAP12Http" originalBindingStyle="document"/>
        <generatedXSD location="Xcalibur_ConsultaProveedores.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation> 
<wsdl:types>
   <xsd:schema targetNamespace="http://www.caracoltv.com.co/TI/xcalibur/consultaproveedores/"
			xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
			<xsd:include schemaLocation="Xcalibur_ConsultaProveedores.xsd" />
    </xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
		schemaLocation="ebms-header-3_0-200704.xsd"/>
	</xsd:schema>	
</wsdl:types>	  
	  
 <!-- Request message -->
	<wsdl:message name="msgConsultaProveedoresRequest">
    	<wsdl:part element="srv:ConsultaProveedoresRequest" name="ConsultaProveedoresRequest"/>
  	</wsdl:message>
  	
  	<!-- Response message -->
  	<wsdl:message name="msgConsultaProveedoresResponse">
    	<wsdl:part element="srv:ConsultaProveedoresResponse" name="ConsultaProveedoresResponse"/>

  	</wsdl:message>
	
	<!-- Fault message -->
	<wsdl:message name="msgConsultaProveedoresFault">
  		<wsdl:part element="eb:Messaging" name="detail"/>
  	</wsdl:message>
  	  
	
<!-- Port type -->
  	<wsdl:portType name="ptConsultaProveedores">
    	<wsdl:operation name="ConsultaProveedores">
      		<wsdl:input message="srv:msgConsultaProveedoresRequest" name="ConsultaProveedores_Input"/>
      		<wsdl:output message="srv:msgConsultaProveedoresResponse" name="ConsultaProveedores_Output"/>
	        <wsdl:fault message="srv:msgConsultaProveedoresFault" name="fault"/>		
	    </wsdl:operation>
  	</wsdl:portType>


    	
<!-- Binding (SOAP 1.2/HTTP binding) -->
	<wsdl:binding name="bdxcaliburconsultaProveedoresSOAP12Http" type="srv:ptConsultaProveedores">
    	<S12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ConsultaProveedores">
	      	<S12:operation soapAction="http://www.caracoltv.com.co/TI/xcalibur/consultaproveedores/"/>
	      	<wsdl:input name="ConsultaProveedores_Input">
	        	<S12:body parts="ConsultaProveedoresRequest" use="literal"/>
	      	</wsdl:input>
	      	<wsdl:output name="ConsultaProveedores_Output">
	        	<S12:body parts="ConsultaProveedoresResponse" use="literal"/>
	      	</wsdl:output>
	      	<wsdl:fault name="fault">
	      		<S12:fault name="fault" use="literal"/>
	      	</wsdl:fault>		
    	</wsdl:operation>
	</wsdl:binding>
	
    <!-- Service -->
  	<wsdl:service name="consultaProveedores">    	
    	
    	<wsdl:port binding="srv:bdxcaliburconsultaProveedoresSOAP12Http" name="ptConsultaProveedores12">
      		<S12:address location="http://localhost:7800/services/s12/dominio/xcaliburconsultaproveedores"/>
    	</wsdl:port>
  	</wsdl:service>  	  
</wsdl:definitions>