<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
name="ConsultaOrdenesInternas" 
targetNamespace="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/consultaproducciones/" 
xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
xmlns:mex="http://www.cysce.com/csif-msg/ca/fault/v1.0/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:srv="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/consultaproducciones/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="bdConsultaproduccionHttp" originalBindingStyle="document"/>
        <generatedXSD location="ConsultaProducciones.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation> 
	  
<wsdl:types>
   <xsd:schema targetNamespace="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/consultaproducciones/"
			xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
			<xsd:include schemaLocation="ConsultaProducciones.xsd" />
    </xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
		schemaLocation="ebms-header-3_0-200704.xsd"/>
	</xsd:schema>	
</wsdl:types>	  
	  
 <!-- Request message -->
	<wsdl:message name="msgConsultaProduccionesRequest">
    	<wsdl:part element="srv:ConsultaProduccionesRequest" name="ConsultaProduccionesRequest"/>
  	</wsdl:message>
  	
  	<!-- Response message -->
  	<wsdl:message name="msgConsultaProduccionesResponse">
    	<wsdl:part element="srv:ConsultaProduccionesResponse" name="ConsultaProduccionesResponse"/>
  	</wsdl:message>
	
	<!-- Fault message -->
	<wsdl:message name="msgConsultaProduccionesFault">
  		<wsdl:part element="eb:Messaging" name="detail"/>
  	</wsdl:message>
  	  
	
<!-- Port type -->
  	<wsdl:portType name="ptConsultaProducciones12">
    	<wsdl:operation name="ConsultaProducciones">
      		<wsdl:input message="srv:msgConsultaProduccionesRequest" name="ConsultaProducciones_Input"/>
      		<wsdl:output message="srv:msgConsultaProduccionesResponse" name="ConsultaProducciones_Output"/>
	        <wsdl:fault message="srv:msgConsultaProduccionesFault" name="fault"/>		
	    </wsdl:operation>
  	</wsdl:portType>
	
    <!-- Service -->
    <wsdl:binding name="bdConsultaproduccionHttp" type="srv:ptConsultaProducciones12">
    	<S12:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="ConsultaProducciones">
	      	<S12:operation soapAction="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/consultaproducciones/"/>
	      	<wsdl:input name="ConsultaProducciones_Input">
	        	<S12:body parts="ConsultaProduccionesRequest" use="literal"/>
	      	</wsdl:input>
	      	<wsdl:output name="ConsultaProducciones_Output">
	        	<S12:body parts="ConsultaProduccionesResponse" use="literal"/>
	      	</wsdl:output>
	      	<wsdl:fault name="fault">
	      		<S12:fault name="fault" use="literal"/>
	      	</wsdl:fault>		
    	</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ConsultaProducciones">    	    	
    	<wsdl:port binding="srv:bdConsultaproduccionHttp" name="ConsultaProduccionescrc">
      		<S12:address location="http://localhost:7800/services/s12/ventasinternacionales/ConsultaProducciones"/>
    	</wsdl:port>
  	</wsdl:service>  	  
</wsdl:definitions>