<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
name="CUDA2" 
targetNamespace="http://www.caracoltv.com.co/ti/gestionarusuarios/crearusuariodominio/" 
xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
xmlns:mex="http://www.cysce.com/csif-msg/ca/fault/v1.0/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:srv="http://www.caracoltv.com.co/ti/gestionarusuarios/crearusuariodominio/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="bdCrearUsuarioDirectorioActivoHttp" originalBindingStyle="document"/>
        <generatedXSD location="CrearUsuarioDirectorioActivo.xsd"/>
        
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation> 
	  	 
<wsdl:types>
   <xsd:schema targetNamespace="http://www.caracoltv.com.co/ti/gestionarusuarios/crearusuariodominio/"   
			xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
			<xsd:include schemaLocation="CrearUsuarioDirectorioActivo.xsd" />			
    </xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 	schemaLocation="ebms-header-3_0-200704.xsd"/>
	</xsd:schema>	
</wsdl:types>	  
	  
 <!-- Request message -->
	<wsdl:message name="msgCUDARequest">
    	<wsdl:part element="srv:CrearUsuarioDominioRequest" name="CUDARequest" />
    	<wsdl:part element="srv:TokenRequest" name="TokenRequest" />
  	</wsdl:message>
  	
  	<!-- Response message -->
  	<wsdl:message name="msgCUDAResponse">
    	<wsdl:part element="srv:CrearUsuarioDominioResponse" name="CUDAResponse"/>    	
  	</wsdl:message>
	
	<!-- Fault message -->
	<wsdl:message name="msgCUDAsFault">
  		<wsdl:part element="eb:Messaging" name="detail"/>
  	</wsdl:message>
  	  
	
<!-- Port type -->
  	<wsdl:portType name="portCUDA">
    	<wsdl:operation name="CUDA2">
      		<wsdl:input message="srv:msgCUDARequest" name="CUDA"/>
      		<wsdl:output message="srv:msgCUDAResponse" name="CUDA_Output"/>
	        <wsdl:fault message="srv:msgCUDAsFault" name="fault"/>		
	    </wsdl:operation>
  	</wsdl:portType>
	
    <!-- Service -->
    <wsdl:binding name="bdCrearUsuarioDirectorioActivoHttp"
    	type="srv:portCUDA">
		<S12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CUDA2">
		<S12:operation soapAction="http://www.caracoltv.com.co/ti/gestionarusuarios/crearusuariodominio/"/>
			<wsdl:input name="CUDA">
				<S12:header message="srv:msgCUDARequest" part="TokenRequest" use="literal"/>
				
				<S12:body parts="CUDARequest" use="literal"/>
			</wsdl:input>
			<wsdl:output name="CUDA_Output">
				<S12:body parts="CUDAResponse" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="fault">
				<S12:fault name="fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CUDA2">    	    	
    	<wsdl:port binding="srv:bdCrearUsuarioDirectorioActivoHttp" name="portCUDA">
      		<S12:address location="http://localhost:7800/services/s12/ti/CUDA2"/>
    	</wsdl:port>
  	</wsdl:service>  	  
</wsdl:definitions>