<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
name="PermisosFuncionalidadXusuario" 
targetNamespace="http://www.caracoltv.com.co/TI/seguridad/permisosfuncionalidadxusuario/" 
xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
xmlns:mex="http://www.cysce.com/csif-msg/ca/fault/v1.0/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:srv="http://www.caracoltv.com.co/TI/seguridad/permisosfuncionalidadxusuario/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="bdPermisosFuncionalidadXusuarioHttp" originalBindingStyle="document"/>
        <generatedXSD location="seguridad_PermisosFuncionalidadXusuario.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation> 
	  
<wsdl:types>
   <xsd:schema targetNamespace="http://www.caracoltv.com.co/TI/seguridad/permisosfuncionalidadxusuario/"
			xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
			<xsd:include schemaLocation="seguridad_PermisosFuncionalidadXusuario.xsd" />
    </xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
		schemaLocation="ebms-header-3_0-200704.xsd"/>
	</xsd:schema>	
</wsdl:types>	  
	  
 <!-- Request message -->
	<wsdl:message name="msgPermisosFuncionalidadXUsuarioRequest">
    	<wsdl:part element="srv:PermisosFuncionalidadXUsuarioRequest" name="PermisosFuncionalidadXUsuarioRequest"/>
  	</wsdl:message>
  	
  	<!-- Response message -->
  	<wsdl:message name="msgPermisosFuncionalidadXUsuarioResponse">
    	<wsdl:part element="srv:PermisosFuncionalidadXUsuarioResponse" name="PermisosFuncionalidadXUsuarioResponse"/>
  	</wsdl:message>
	
	<!-- Fault message -->
	<wsdl:message name="msgPermisosFuncionalidadXUsuarioFault">
  		<wsdl:part element="eb:Messaging" name="detail"/>
  	</wsdl:message>
  	  
	
<!-- Port type -->
  	<wsdl:portType name="ptPermisosFuncionalidadXusuario12">
    	<wsdl:operation name="operacionpermisosfuncionalidadxusuario">
      		<wsdl:input message="srv:msgPermisosFuncionalidadXUsuarioRequest" name="PermisosFuncionalidadXUsuario_Input"/>
      		<wsdl:output message="srv:msgPermisosFuncionalidadXUsuarioResponse" name="PermisosFuncionalidadXUsuario_Output"/>
	        <wsdl:fault message="srv:msgPermisosFuncionalidadXUsuarioFault" name="fault"/>		
	    </wsdl:operation>
  	</wsdl:portType>
	
    <!-- Service -->
    <wsdl:binding name="bdPermisosFuncionalidadXusuarioHttp" type="srv:ptPermisosFuncionalidadXusuario12">
    	<S12:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="operacionpermisosfuncionalidadxusuario">
	      	<S12:operation soapAction="http://www.caracoltv.com.co/TI/seguridad/permisosfuncionalidadxusuario/"/>
	      	<wsdl:input name="PermisosFuncionalidadXUsuario_Input">
	        	<S12:body parts="PermisosFuncionalidadXUsuarioRequest" use="literal"/>
	      	</wsdl:input>
	      	<wsdl:output name="PermisosFuncionalidadXUsuario_Output">
	        	<S12:body parts="PermisosFuncionalidadXUsuarioResponse" use="literal"/>
	      	</wsdl:output>
	      	<wsdl:fault name="fault">
	      		<S12:fault name="fault" use="literal"/>
	      	</wsdl:fault>		
    	</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="permisosfuncionalidadxusuario">    	    	
    	<wsdl:port binding="srv:bdPermisosFuncionalidadXusuarioHttp" name="permisosfuncionalidadxusuario">
      		<S12:address location="http://localhost:7800/services/s12/dominio/permisosfuncionalidadxusuario"/>
    	</wsdl:port>
  	</wsdl:service>  	  
</wsdl:definitions>