<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="crearproveedor"  
targetNamespace="http://www.caracoltv.com.co/ti/mdm/proveedor/crearproveedor/" 
xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
xmlns:mex="http://www.cysce.com/csif-msg/ca/fault/v1.0/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:srv="http://www.caracoltv.com.co/ti/mdm/proveedor/crearproveedor/"
xmlns:canonico="http://www.caracoltv.com.co/ti/mdm/canonico/proveedor/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">        
        <binding hasEncoding="false" imported="true" name="bdcrearproveedorSOAP12Http" 
        originalBindingStyle="document"/>
        <generatedXSD location="Proveedor.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  
  
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.caracoltv.com.co/ti/mdm/canonico/proveedor/"
			xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
			<xsd:include schemaLocation="Proveedor.xsd" />
	</xsd:schema>
	<xsd:schema>
    <xsd:import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 	schemaLocation="ebms-header-3_0-200704.xsd"/>
    </xsd:schema>		
</wsdl:types>
  

 <!-- Request message -->
	<wsdl:message name="msgcrearproveedorRequest">
    	<wsdl:part element="canonico:Proveedor" name="crearproveedorRequest"/>
  	</wsdl:message>  	
  	<!-- Response message -->
  	<wsdl:message name="msgcrearproveedorResponse">
    	<wsdl:part element="canonico:Resultado" name="crearproveedorResponse"/>
  	</wsdl:message>	
	<!-- Fault message -->
	<wsdl:message name="msgcrearproveedorFault">
<!--  		<wsdl:part element="mex:messageException" name="messageException"/>	-->
  		<wsdl:part element="eb:Messaging" name="detail"/>
  	</wsdl:message>
  
  


<!-- Port type -->
  	<wsdl:portType name="ptcrearproveedor">
    	<wsdl:operation name="crearproveedor">
      		<wsdl:input message="srv:msgcrearproveedorRequest" name="crearproveedor_Input"/>
      		<wsdl:output message="srv:msgcrearproveedorResponse" name="crearproveedor_Output"/>
	        <wsdl:fault message="srv:msgcrearproveedorFault" name="fault"/>		
	    </wsdl:operation>
  	</wsdl:portType>
  	



    	
<!-- Binding (SOAP 1.2/HTTP binding) -->
	<wsdl:binding name="bdcrearproveedorSOAP12Http" type="srv:ptcrearproveedor">
    	<S12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="crearproveedor">
	      	<S12:operation soapAction="http://www.caracoltv.com.co/ti/mdm/proveedor/crearproveedor/"/>
	      	<wsdl:input name="crearproveedor_Input">
	        	<S12:body parts="crearproveedorRequest" use="literal"/>
	      	</wsdl:input>
	      	<wsdl:output name="crearproveedor_Output">
	        	<S12:body parts="crearproveedorResponse" use="literal"/>
	      	</wsdl:output>
	      	<wsdl:fault name="fault">
	      		<S12:fault name="fault" use="literal"/>
	      	</wsdl:fault>		
    	</wsdl:operation>
	</wsdl:binding>
	

<!-- Service -->
  	<wsdl:service name="creaproveedor">    	    	
    	<wsdl:port binding="srv:bdcrearproveedorSOAP12Http" name="ptcrearproveedor12">
            <S12:address location="http://localhost:7800/services/s12/ti/mdm/proveedor/crearproveedor"/>
        </wsdl:port>
  	</wsdl:service>  
  	


</wsdl:definitions>