<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="BuscarTalento" targetNamespace="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="BasicHttpBinding_IBuscarTalentoXCodigo" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import namespace="http://tempuri.org/" schemaLocation="RemoteFiles/xsd_xsd0.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IBuscarTalentoXCodigo_BuscarTalentoXCodigo_InputMessage">
    <wsdl:part element="tns:BuscarTalentoXCodigo" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="IBuscarTalentoXCodigo_BuscarTalentoXCodigo_OutputMessage">
    <wsdl:part element="tns:BuscarTalentoXCodigoResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="IBuscarTalentoXCodigo">
    <wsdl:operation name="BuscarTalentoXCodigo">
      <wsdl:input message="tns:IBuscarTalentoXCodigo_BuscarTalentoXCodigo_InputMessage" wsaw:Action="http://tempuri.org/IBuscarTalentoXCodigo/BuscarTalentoXCodigo"/>
      <wsdl:output message="tns:IBuscarTalentoXCodigo_BuscarTalentoXCodigo_OutputMessage" wsaw:Action="http://tempuri.org/IBuscarTalentoXCodigo/BuscarTalentoXCodigoResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IBuscarTalentoXCodigo" type="tns:IBuscarTalentoXCodigo">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="BuscarTalentoXCodigo">
      <soap:operation soapAction="http://tempuri.org/IBuscarTalentoXCodigo/BuscarTalentoXCodigo" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BuscarTalento">
    <wsdl:port binding="tns:BasicHttpBinding_IBuscarTalentoXCodigo" name="BasicHttpBinding_IBuscarTalentoXCodigo">
      <soap:address location="http://srvpint02:85/WsIndiceTalento/BuscarTalentoXCodigo/BuscarTalentoXCodigo.svc"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>