<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ConsultaCertificadoLaboralXcalibur" targetNamespace="http://www.caracoltv.com.co/Xcalibur/NM/CerLaboral" xmlns:S1="urn:soap-fault:details" xmlns:S2="http://www.caracoltv.com.co/Xcalibur/NM/CerLaboral/ConsultaCertificadoLaboralXcalibur" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://www.caracoltv.com.co/Xcalibur/NM/CerLaboral" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<wsdl:documentation>Author=V1.0, EncodingType=DOC_LITERAL, WSA_Product=11.7.1 - Wed Jun 14 18:15:06 EDT 2017<wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="WS_ConsultaCertificadoLaboralProduccion_InlineSchema1.xsd"/>
        <generatedXSD location="WS_ConsultaCertificadoLaboralProduccion_InlineSchema2.xsd"/>
        <binding hasEncoding="false" imported="true" name="ConsultaCertificadoLaboralXcaliburObj" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>


          <schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" targetNamespace="urn:soap-fault:details" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
      <xsd:include schemaLocation="WS_ConsultaCertificadoLaboralProduccion_InlineSchema1.xsd"/>
    </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.caracoltv.com.co/Xcalibur/NM/CerLaboral/ConsultaCertificadoLaboralXcalibur" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
      <xsd:include schemaLocation="WS_ConsultaCertificadoLaboralProduccion_InlineSchema2.xsd"/>
    </schema>
    </wsdl:types>
  <wsdl:message name="FaultDetailMessage">
    <wsdl:part element="S1:FaultDetail" name="FaultDetail"/>
  </wsdl:message>
  <wsdl:message name="ConsultaCertificadoLaboralXcalibur_ConsultarDatosCertificadoResponse">
    <wsdl:part element="S2:ConsultarDatosCertificadoResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="ConsultaCertificadoLaboralXcalibur_ConsultarDatosCertificado">
    <wsdl:part element="S2:ConsultarDatosCertificado" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="ConsultaCertificadoLaboralXcaliburObj">
    <wsdl:operation name="ConsultarDatosCertificado">
      <wsdl:input message="tns:ConsultaCertificadoLaboralXcalibur_ConsultarDatosCertificado"/>
      <wsdl:output message="tns:ConsultaCertificadoLaboralXcalibur_ConsultarDatosCertificadoResponse"/>
      <wsdl:fault message="tns:FaultDetailMessage" name="ConsultaCertificadoLaboralXcaliburFault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultaCertificadoLaboralXcaliburObj" type="tns:ConsultaCertificadoLaboralXcaliburObj">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarDatosCertificado">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ConsultaCertificadoLaboralXcaliburFault">
        <soap:fault name="ConsultaCertificadoLaboralXcaliburFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConsultaCertificadoLaboralXcaliburService">
    <wsdl:port binding="tns:ConsultaCertificadoLaboralXcaliburObj" name="ConsultaCertificadoLaboralXcaliburObj">
<wsdl:documentation/>
      <soap:address location="http://172.17.4.32:8080/wsa/wsa1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>