<?xml version="1.0" encoding="UTF-8"?><!--File Correo-CargaPlantillaV4.wsdl, application Correo-CargaPlantillaV4-CH--><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Correo-AdjuntarPlantilla" targetNamespace="http://www.caracoltv.com.co/TI/correo/cargaplantilla4/" xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:srv="http://www.caracoltv.com.co/TI/correo/cargaplantilla4/" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="bdCargaPlantillaSOAP12Http2" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
<wsdl:types>
		<xsd:schema targetNamespace="http://www.caracoltv.com.co/TI/correo/cargaplantilla4/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="RemoteFiles/xsd_xsd0.xsd"/>
</xsd:schema>
        

    </wsdl:types>	  
	  
 
	<wsdl:message name="msgCargaPlantillaRequest">
    	<wsdl:part element="srv:CargaPlantillaRequest" name="CargaPlantillaRequest"/>

  	</wsdl:message>
  	


  	<wsdl:portType name="ptCargaPlantillav4">
    	<wsdl:operation name="CargaPlantillav4">
      		<wsdl:input message="srv:msgCargaPlantillaRequest" name="CargaPlantilla_Input"/>
	    </wsdl:operation>
  	</wsdl:portType>
    	

	<wsdl:binding name="bdCargaPlantillaSOAP12Http2" type="srv:ptCargaPlantillav4">
    	<S12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="CargaPlantillav4">
	      	<S12:operation soapAction="http://www.caracoltv.com.co/TI/correo/cargaplantilla4/"/>
	      	<wsdl:input name="CargaPlantilla_Input">
	        	<S12:body parts="CargaPlantillaRequest" use="literal"/>
	      	</wsdl:input>
	      	
    	</wsdl:operation>
	</wsdl:binding>
    
  	<wsdl:service name="CargaPlantillav4">
    	
    	
    	<wsdl:port binding="srv:bdCargaPlantillaSOAP12Http2" name="ptCargaPlantilla12">
      		<S12:address location="http://srviibpr:7800/services/s12/correo/cargaplantillav4"/>
    	</wsdl:port>
  	</wsdl:service>  	

</wsdl:definitions>