<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
name="ConsultaOrdenesInternas" 
targetNamespace="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/consultaproduccionesxcontratoid/" 
xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
xmlns:mex="http://www.cysce.com/csif-msg/ca/fault/v1.0/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:srv="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/consultaproduccionesxcontratoid/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="bdConsultaProduccionesXContratoIdHttp" originalBindingStyle="document"/>
        <generatedXSD location="ConsultaProduccionesXContratoId.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation> 
	  
<wsdl:types>
   <xsd:schema targetNamespace="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/consultaproduccionesxcontratoid/"
			xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
			<xsd:include schemaLocation="ConsultaProduccionesXContratoId.xsd" />
    </xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
		schemaLocation="ebms-header-3_0-200704.xsd"/>
	</xsd:schema>	
</wsdl:types>	  
	  
 <!-- Request message -->
	<wsdl:message name="msgConsultaProduccionesXContratoIdsRequest">
    	<wsdl:part element="srv:consultaproduccionesxcontratoidRequest" name="ConsultaProduccionesXContratoIdsRequest"/>
  	</wsdl:message>
  	
  	<!-- Response message -->
  	<wsdl:message name="msgConsultaProduccionesXContratoIdsResponse">
    	<wsdl:part element="srv:consultaproduccionesxcontratoidResponse" name="ConsultaProduccionesXContratoIdsResponse"/>
  	</wsdl:message>
	
	<!-- Fault message -->
	<wsdl:message name="msgConsultaProduccionesXContratoIdsFault">
  		<wsdl:part element="eb:Messaging" name="detail"/>
  	</wsdl:message>
  	  
	
<!-- Port type -->
  	<wsdl:portType name="ptConsultaProduccionesXContratoIds12">
    	<wsdl:operation name="ConsultaProducciones">
      		<wsdl:input message="srv:msgConsultaProduccionesXContratoIdsRequest" name="ConsultaProduccionesXContratoIds_Input"/>
      		<wsdl:output message="srv:msgConsultaProduccionesXContratoIdsResponse" name="ConsultaProduccionesXContratoIds_Output"/>
	        <wsdl:fault message="srv:msgConsultaProduccionesXContratoIdsFault" name="fault"/>		
	    </wsdl:operation>
  	</wsdl:portType>
	
    <!-- Service -->
    <wsdl:binding name="bdConsultaProduccionesXContratoIdHttp" type="srv:ptConsultaProduccionesXContratoIds12">
    	<S12:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="ConsultaProducciones">
	      	<S12:operation soapAction="http://www.caracoltv.com.co/ventasinternacionales/gestionmovimientos/ConsultaProduccionesXContratoId/"/>
	      	<wsdl:input name="ConsultaProduccionesXContratoIds_Input">
	        	<S12:body parts="ConsultaProduccionesXContratoIdsRequest" use="literal"/>
	      	</wsdl:input>
	      	<wsdl:output name="ConsultaProduccionesXContratoIds_Output">
	        	<S12:body parts="ConsultaProduccionesXContratoIdsResponse" use="literal"/>
	      	</wsdl:output>
	      	<wsdl:fault name="fault">
	      		<S12:fault name="fault" use="literal"/>
	      	</wsdl:fault>		
    	</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ConsultaProduccionesXContratoId">    	    	
    	<wsdl:port binding="srv:bdConsultaProduccionesXContratoIdHttp" name="ConsultaProduccionesXContratoId">
      		<S12:address location="http://srviibpr:7800/services/s12/ventasinternacionales/ConsultaProduccionesXContratoId"/>
    	</wsdl:port>
  	</wsdl:service>  	  
</wsdl:definitions>