<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
name="ConsultaUsuarioDominioXLoginYCedula" 
targetNamespace="http://www.caracoltv.com.co/ti/gestionarusuarios/consultausuariodominioxloginycedula/" 
xmlns:S11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:S12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 
xmlns:mex="http://www.cysce.com/csif-msg/ca/fault/v1.0/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:srv="http://www.caracoltv.com.co/ti/gestionarusuarios/consultausuariodominioxloginycedula/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="bdConsultaUsuarioDominioXLoginYCedulaHttp" 
        originalBindingStyle="document"/>
        <generatedXSD location="consultausuariodominioxloginycedula.xsd"/>
        
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation> 
	  	 
<wsdl:types>
   <xsd:schema targetNamespace="http://www.caracoltv.com.co/ti/gestionarusuarios/consultausuariodominioxloginycedula/"   
			xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
			<xsd:include schemaLocation="consultausuariodominioxloginycedula.xsd" />			
    </xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" 	
		schemaLocation="ebms-header-3_0-200704.xsd"/>
	</xsd:schema>	
</wsdl:types>	  
	  
 <!-- Request message -->
	<wsdl:message name="msgConsultaUsuarioDominioXLoginYCedulasRequest">
    	<wsdl:part element="srv:ConsultaUsuarioDominioXLoginYCedulaRequest" name="ConsultaUsuarioDominioXLoginYCedulasRequest"/>
    	
  	</wsdl:message>
  	
  	<!-- Response message -->
  	<wsdl:message name="msgConsultaUsuarioDominioXLoginYCedulasResponse">
    	<wsdl:part element="srv:ConsultaUsuarioDominioXLoginYCedulaResponse" name="ConsultaUsuarioDominioXLoginYCedulasResponse"/>    	
  	</wsdl:message>
	
	<!-- Fault message -->
	<wsdl:message name="msgConsultaUsuarioDominioXLoginYCedulasFault">
  		<wsdl:part element="eb:Messaging" name="detail"/>
  	</wsdl:message>
  	  
	
<!-- Port type -->
  	<wsdl:portType name="ptConsultaUsuarioDominioXLoginYCedulas12">
    	<wsdl:operation name="ConsultaUsuarioDominioXLoginYCedula">
      		<wsdl:input message="srv:msgConsultaUsuarioDominioXLoginYCedulasRequest" name="ConsultaUsuarioDominioXLoginYCedula"/>
      		<wsdl:output message="srv:msgConsultaUsuarioDominioXLoginYCedulasResponse" name="ConsultaUsuarioDominioXLoginYCedulas_Output"/>
	        <wsdl:fault message="srv:msgConsultaUsuarioDominioXLoginYCedulasFault" name="fault"/>		
	    </wsdl:operation>
  	</wsdl:portType>
	
    <!-- Service -->
    <wsdl:binding name="bdConsultaUsuarioDominioXLoginYCedulaHttp" type="srv:ptConsultaUsuarioDominioXLoginYCedulas12">
    	<S12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="ConsultaUsuarioDominioXLoginYCedula">
	      	<S12:operation  soapAction="http://www.caracoltv.com.co/ti/seguridad/ConsultaUsuarioDominioXLoginYCedula/"/>	      	
	      	<wsdl:input name="ConsultaUsuarioDominioXLoginYCedula">
	      	    
	      	    	      	 		   
	        	<S12:body parts="ConsultaUsuarioDominioXLoginYCedulasRequest" use="literal"/>
	      	</wsdl:input>
	      	<wsdl:output name="ConsultaUsuarioDominioXLoginYCedulas_Output">
	        	<S12:body parts="ConsultaUsuarioDominioXLoginYCedulasResponse" use="literal"/>
	      	</wsdl:output>
	      	<wsdl:fault name="fault">
	      		<S12:fault name="fault" use="literal"/>
	      	</wsdl:fault>		
    	</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ConsultaUsuarioDominioXLoginYCedulas">    	    	
    	<wsdl:port binding="srv:bdConsultaUsuarioDominioXLoginYCedulaHttp" name="ConsultaUsuarioDominioXLoginYCedulascrc">
      		<S12:address location="http://localhost:7800/services/s12/ti/ConsultaUsuarioDominioXLoginYCedula"/>
    	</wsdl:port>
  	</wsdl:service>  	  
</wsdl:definitions>